<!DOCTYPE html>
<html lang="es">

  <head>
    <meta charset="UTF-8" />
    <title>USUARIOS</title>
    <link rel="stylesheet" href="css/style.css">
  </head>

  <body>
    <img src="images/logo_mvc.png" alt="" class="logo">

    <nav>
      <ul>
        <li><a href="index.php?controlador=usuarios">Listar usuarios</a></li>
        <li><a href="index.php?controlador=usuarios&accion=crearusuario">Crear usuario</a></li>
        <li><a href="index.php?controlador=login&accion=salir">Salir</a></li>
      </ul>
    </nav>
