<?php
  require_once("views/header.phtml");
?>


    <form class="" action="index.php?controlador=usuarios&accion=guardarnuevousuario" method="post">
      <p>
        nombre: <input type="text" name="nombre" value="">
      </p>

      <p>
        email: <input type="text" name="email" value="">
      </p>

      <p>
        Password:<input type="password" name="password" value="">
      </p>

      <p>
        Rol:
        <select class="" name="rol">
          <option value="administrador">Administrador</option>
          <option value="tecnico">Técnico</option>
        </select>
      </p>

      <p>

        <input type="submit" name="" value="Guardar Usuario">
      </p>

    </form>

    <?php
      require_once("views/footer.phtml");
    ?>
