<?php
  require_once("views/header.phtml");
?>

<form class="" action="index.php?controlador=login&accion=ingresar" method="post">

  <p>
      Usuario(email): <input type="text" name="email" value="" >
  </p>

  <p>
      Password: <input type="text" name="password" value="" >
  </p>

  <p>
    <input type="submit" name="" value="Ingresar">
  </p>

  <p>
    <?php
      echo ( isset($datos['error'])? $datos['error'] : "");
     ?>
  </p>

</form>


<?php
  require_once("views/footer.phtml");
?>
